@startuml

node "backend" {
  [KLE]
  [Fordelinger]
  [Organisation]
  [API]
}

database "PostgreSQL" {
  [data]
}

[frontend] -- HTTP
HTTP - [KLE]
HTTP - [Fordelinger]
HTTP - [Organisation]

[KommuneSystem] -- REST
REST -- [API]

[KLE] -- dataAccess
[Fordelinger] -- dataAccess
[Organisation] -- dataAccess
dataAccess -- [data]


@enduml